"""Sample tests: mock exam papers per unit (multiple choice + short answer + extended response).

Papers are generated by Gemma, verified, and shared through the curriculum library. A student's attempt snapshots
the paper; multiple choice is marked on submit and the student self-marks written answers against the
marking scheme, which (like the answer key) is only revealed after submitting."""
import json
from datetime import datetime, timedelta
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_approved_student
from app.api.routes.curriculum import _ai_http_error, _get_unit
from app.api.routes.subjects import own_subject
from app.db.database import get_db
from app.models.models import CurriculumUnit, SampleTest, SampleTestAttempt, Student, Subject
from app.schemas.schemas import (
    SampleTestListOut, SampleTestSummaryOut, SampleTestSectionSummary, SampleTestAttemptOut, STSectionOut,
    STQuestionOut, MarkingPoint, SampleTestStartRequest, SampleTestSubmitRequest, SelfMarkRequest,
)
from app.services import ai_service, curriculum_library

router = APIRouter(tags=["sample-tests"])

MAX_SAMPLE_TESTS = 5
_MAX_WRITTEN_ANSWER = 5000
_LATE_GRACE = timedelta(seconds=30)


# ─── helpers ──────────────────────────────────────────────────────────────────

def _section_marks(sec: dict) -> int:
    return sum(q["marks"] for q in sec["questions"])


def _summary(t: SampleTest, attempts: list[SampleTestAttempt]) -> SampleTestSummaryOut:
    paper = json.loads(t.paper_json)
    mine = [a for a in attempts if a.sample_test_id == t.id]
    finished = [a for a in mine if a.marked_at and a.total_marks]
    open_attempt = next((a for a in sorted(mine, key=lambda a: a.started_at, reverse=True) if not a.submitted_at), None)
    return SampleTestSummaryOut(
        id=t.id, number=t.number, title=paper["title"], duration_minutes=paper["duration_minutes"],
        total_marks=paper["total_marks"],
        sections=[SampleTestSectionSummary(title=s["title"], type=s["type"], questions=len(s["questions"]),
                                           marks=_section_marks(s)) for s in paper["sections"]],
        attempts=len([a for a in mine if a.submitted_at]),
        best_percent=max((round(100 * ((a.mcq_score or 0) + (a.written_score or 0)) / a.total_marks) for a in finished), default=None),
        in_progress_attempt_id=open_attempt.id if open_attempt else None,
    )


async def _local_tests(unit: CurriculumUnit, db: AsyncSession) -> list[SampleTest]:
    return list((await db.execute(
        select(SampleTest).where(SampleTest.unit_id == unit.id).order_by(SampleTest.number)
    )).scalars().all())


async def _sync_from_library(subject: Subject, unit: CurriculumUnit, local: list[SampleTest], db: AsyncSession) -> list[SampleTest]:
    """Copy any shared papers this student doesn't have yet (no AI call)."""
    key = subject.curriculum_library_key
    if not key:
        return local
    entry = await curriculum_library.lookup(key)
    units = entry["units"] if entry else []
    shared = units[unit.position] if unit.position < len(units) else None
    if not shared or shared.get("title") != unit.title:
        return local
    have = {t.number for t in local}
    added = False
    for n, paper in enumerate(shared.get("sample_tests") or [], 1):
        if n not in have and isinstance(paper, dict) and paper.get("sections"):
            db.add(SampleTest(unit_id=unit.id, number=n, paper_json=json.dumps(paper)))
            added = True
    if added:
        await db.flush()
        return await _local_tests(unit, db)
    return local


def _expires_at(a: SampleTestAttempt) -> Optional[datetime]:
    return a.started_at + timedelta(minutes=a.time_limit_minutes) if a.time_limit_minutes else None


def _attempt_out(a: SampleTestAttempt) -> SampleTestAttemptOut:
    paper = json.loads(a.paper_json)
    answers, marks = json.loads(a.answers_json or "{}"), json.loads(a.self_marks_json or "{}")
    revealed = a.submitted_at is not None
    sections, mcq_marks, written_marks = [], 0, 0
    for sec in paper["sections"]:
        qs = []
        for q in sec["questions"]:
            is_mcq = sec["type"] == "mcq"
            ans = answers.get(q["id"])
            out = STQuestionOut(id=q["id"], type=sec["type"], question=q["question"], marks=q["marks"],
                                options=q["options"] if is_mcq else None, your_answer=ans)
            if revealed:
                if is_mcq:
                    out.correct_answer, out.correct, out.explanation = q["answer"], ans == q["answer"], q.get("explanation")
                else:
                    out.model_answer = q["model_answer"]
                    out.marking_points = [MarkingPoint(**p) for p in q["marking_points"]]
                    out.awarded = marks.get(q["id"])
            qs.append(out)
            if is_mcq:
                mcq_marks += q["marks"]
            else:
                written_marks += q["marks"]
        sections.append(STSectionOut(id=sec["id"], title=sec["title"], type=sec["type"],
                                     instructions=sec.get("instructions", ""), marks=_section_marks(sec), questions=qs))
    total = (a.mcq_score or 0) + (a.written_score or 0) if a.marked_at else None
    return SampleTestAttemptOut(
        id=a.id, subject_id=a.subject_id, unit_title=a.unit_title, number=a.number, title=paper["title"],
        instructions=paper.get("instructions", ""), duration_minutes=paper["duration_minutes"],
        total_marks=a.total_marks, time_limit_minutes=a.time_limit_minutes, started_at=a.started_at,
        expires_at=_expires_at(a), submitted_at=a.submitted_at, marked_at=a.marked_at, timed_out=a.timed_out,
        mcq_score=a.mcq_score, mcq_marks=mcq_marks, written_score=a.written_score, written_marks=written_marks,
        total_score=total, sections=sections,
    )


async def _own_attempt(attempt_id: int, student: Student, db: AsyncSession) -> SampleTestAttempt:
    a = await db.get(SampleTestAttempt, attempt_id)
    if not a or a.student_id != student.id:
        raise HTTPException(status_code=404, detail="Attempt not found")
    return a


async def _own_sample_test(test_id: int, student: Student, db: AsyncSession) -> tuple[SampleTest, CurriculumUnit, Subject]:
    t = await db.get(SampleTest, test_id)
    unit = await db.get(CurriculumUnit, t.unit_id) if t else None
    subject = await db.get(Subject, unit.subject_id) if unit else None
    if not t or not subject or subject.student_id != student.id:
        raise HTTPException(status_code=404, detail="Sample test not found")
    return t, unit, subject


async def _list(student: Student, subject: Subject, unit: CurriculumUnit, tests: list[SampleTest], db: AsyncSession) -> SampleTestListOut:
    attempts = list((await db.execute(
        select(SampleTestAttempt).where(SampleTestAttempt.student_id == student.id,
                                        SampleTestAttempt.sample_test_id.in_([t.id for t in tests] or [0]))
    )).scalars().all())
    return SampleTestListOut(tests=[_summary(t, attempts) for t in tests],
                             can_generate=len(tests) < MAX_SAMPLE_TESTS, limit=MAX_SAMPLE_TESTS)


# ─── routes ───────────────────────────────────────────────────────────────────

@router.get("/subjects/{subject_id}/curriculum/units/{unit_id}/sample-tests", response_model=SampleTestListOut)
async def list_sample_tests(subject_id: int, unit_id: int, student: Student = Depends(get_approved_student),
                            db: AsyncSession = Depends(get_db)):
    subject = await own_subject(subject_id, student, db)
    unit = await _get_unit(subject_id, unit_id, db)
    tests = await _sync_from_library(subject, unit, await _local_tests(unit, db), db)
    return await _list(student, subject, unit, tests, db)


@router.post("/subjects/{subject_id}/curriculum/units/{unit_id}/sample-tests", response_model=SampleTestListOut)
async def generate_sample_test(subject_id: int, unit_id: int, student: Student = Depends(get_approved_student),
                               db: AsyncSession = Depends(get_db)):
    """Write a new sample test for this unit (up to MAX_SAMPLE_TESTS, shared with the student's category)."""
    subject = await own_subject(subject_id, student, db)
    unit = await _get_unit(subject_id, unit_id, db)
    tests = await _sync_from_library(subject, unit, await _local_tests(unit, db), db)
    if len(tests) >= MAX_SAMPLE_TESTS:
        raise HTTPException(status_code=409, detail=f"This unit already has {MAX_SAMPLE_TESTS} sample tests.")

    avoid = [q["question"][:120] for t in tests for s in json.loads(t.paper_json)["sections"] for q in s["questions"]]
    details = json.loads(unit.details_json) if unit.details_json else None
    try:
        paper = await ai_service.generate_sample_test(student, subject, unit, details, avoid)
    except (ai_service.AIUnavailableError, ValueError, KeyError, TypeError, RuntimeError, OSError) as e:
        raise _ai_http_error(e)

    number = len(tests) + 1
    if subject.curriculum_library_key:
        shared_number = await curriculum_library.publish_sample_test(
            subject.curriculum_library_key, unit.position, unit.title, paper, MAX_SAMPLE_TESTS)
        if shared_number:
            number = shared_number
    if number in {t.number for t in tests}:      # someone else's paper took this slot meanwhile
        number = max(t.number for t in tests) + 1
    db.add(SampleTest(unit_id=unit.id, number=number, paper_json=json.dumps(paper)))
    await db.flush()
    tests = await _sync_from_library(subject, unit, await _local_tests(unit, db), db)
    return await _list(student, subject, unit, tests, db)


@router.post("/sample-tests/{test_id}/attempts", response_model=SampleTestAttemptOut)
async def start_sample_test(test_id: int, payload: SampleTestStartRequest = SampleTestStartRequest(),
                            student: Student = Depends(get_approved_student), db: AsyncSession = Depends(get_db)):
    t, unit, subject = await _own_sample_test(test_id, student, db)
    paper = json.loads(t.paper_json)
    a = SampleTestAttempt(
        student_id=student.id, subject_id=subject.id, unit_id=unit.id, sample_test_id=t.id, unit_title=unit.title,
        number=t.number, paper_json=t.paper_json, answers_json="{}", self_marks_json="{}",
        total_marks=paper["total_marks"], time_limit_minutes=paper["duration_minutes"] if payload.timed else None,
        started_at=datetime.utcnow(),
    )
    db.add(a)
    await db.flush()
    return _attempt_out(a)


@router.get("/sample-test-attempts/{attempt_id}", response_model=SampleTestAttemptOut)
async def get_sample_test_attempt(attempt_id: int, student: Student = Depends(get_approved_student),
                                  db: AsyncSession = Depends(get_db)):
    return _attempt_out(await _own_attempt(attempt_id, student, db))


@router.post("/sample-test-attempts/{attempt_id}/submit", response_model=SampleTestAttemptOut)
async def submit_sample_test(attempt_id: int, payload: SampleTestSubmitRequest,
                             student: Student = Depends(get_approved_student), db: AsyncSession = Depends(get_db)):
    a = await _own_attempt(attempt_id, student, db)
    if a.submitted_at:
        return _attempt_out(a)
    paper = json.loads(a.paper_json)
    answers: dict = {}
    mcq_score = 0
    for sec in paper["sections"]:
        for q in sec["questions"]:
            given = payload.answers.get(q["id"])
            if sec["type"] == "mcq":
                if isinstance(given, int) and not isinstance(given, bool) and 0 <= given < 4:
                    answers[q["id"]] = given
                    mcq_score += q["marks"] if given == q["answer"] else 0
            elif isinstance(given, str) and given.strip():
                answers[q["id"]] = given.strip()[:_MAX_WRITTEN_ANSWER]
    now = datetime.utcnow()
    expires = _expires_at(a)
    a.timed_out = bool(expires and now > expires + _LATE_GRACE)
    a.answers_json = json.dumps(answers)
    a.mcq_score = mcq_score
    a.submitted_at = now
    await db.flush()
    return _attempt_out(a)


@router.post("/sample-test-attempts/{attempt_id}/self-mark", response_model=SampleTestAttemptOut)
async def self_mark(attempt_id: int, payload: SelfMarkRequest, student: Student = Depends(get_approved_student),
                    db: AsyncSession = Depends(get_db)):
    """Record the marks the student awards their written answers (0..question marks each)."""
    a = await _own_attempt(attempt_id, student, db)
    if not a.submitted_at:
        raise HTTPException(status_code=409, detail="Submit the test before marking it.")
    written = {q["id"]: q["marks"] for sec in json.loads(a.paper_json)["sections"] if sec["type"] != "mcq"
               for q in sec["questions"]}
    marks = {}
    for qid, max_marks in written.items():
        given = payload.marks.get(qid, 0)
        if not isinstance(given, int) or isinstance(given, bool) or not 0 <= given <= max_marks:
            raise HTTPException(status_code=400, detail=f"Marks for {qid} must be between 0 and {max_marks}.")
        marks[qid] = given
    if set(payload.marks) - set(written):
        raise HTTPException(status_code=400, detail="Unknown question.")
    a.self_marks_json = json.dumps(marks)
    a.written_score = sum(marks.values())
    a.marked_at = datetime.utcnow()
    await db.flush()
    return _attempt_out(a)
